spring:
  application:
    name: RegistrationClean

  datasource:
    url: jdbc:postgresql://localhost:5431/RegistrationClean
    username: postgres
    password: Lukinha123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    location: classpath:db/migration